### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by TheAndrewHall** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#364] opened 2023-06-12 23:13 UTC
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#3)

**In which task and step of the codelab can this issue be found?**
Step 4 - "Your setContent block should look like this code snippet"

**Describe the problem**
Code snippet has an invalid reference to an import

**Steps to reproduce?**
1. Go to step 4 of the page on the URL above
2. Examine the code snippet
3. Note that the reference to "MaterialTheme.colors.background" is not a valid reference
4. Replace it with a reference to "MaterialTheme.colorScheme.background" to see the fault corrected

**Versions**
**_Android Studio version:_** 
Android Studio Flamingo | 2022.2.1 Patch 2
Build #AI-222.4459.24.2221.10121639, built on May 12, 2023
Runtime version: 17.0.6+0-b2043.56-9586694 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 4
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    gradle.version.catalogs.dynamic.support=true

_API version of the emulator:_  no idea

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by o-alquimista** [comment] 2023-07-21 02:34
Duplicate of #326

**Closed** 2023-10-09 13:02 UTC
