### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by reknoZ** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#249] opened 2023-03-30 16:48 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#5

**In which task and step of the codelab can this issue be found?**
Task 6, step 4

**Describe the problem**
Just two tasks earlier, you detailed what were valid Composable function names and what were not.

You said: The Compose function must NOT be a nouned preposition, such as: TextFieldWithLink().

In this task/step, you told us to create a new composable function: BirthdayGreetingWithText().

So which is it?

**Steps to reproduce?**
1. Go to page
2. Read the tutorial
3. See error...

**Versions**
irrelevant

**Additional information**

**Comment by osuleymanova** [comment] 2023-04-05 18:03
Duplicate of #214

**Comment by johnshea** [comment] 2023-07-20 14:15
Hi @reknoZ 

Thank you for also bringing this to our attention.

The course content was rewritten to address it and has since been republished.

Regards.

**Closed by johnshea** 2023-07-20 14:15 UTC
