### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by chrishays177** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#215] opened 2023-03-06 13:59 UTC
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#6)

**In which task and step of the codelab can this issue be found?**
In step 7 it asks you to add in a modifier by using
Column(
   modifier = modifier.fillMaxSize()
) {
  //...
}

**Describe the problem**
the corrrect way should be 
modifier = Modifier.fillMaxSize()

without the second modifier being capilizied you willl be presented with an error.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2023-03-06 18:56
Duplicate of #211

**Comment by android-dev-lxl** [comment] 2023-03-07 00:35
@chrishays177 
Thank you for reaching out to us. 
It is a best practice  to use the passed in Modifier argument in the root layout of the composable.
Instructions are updated and to be published

**Closed** 2023-03-07 00:43 UTC
