### ISSUE TITLE
Add images: Android Basics in Compose

### ISSUE THREAD

**Issue by mordeshen** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#154] opened 2023-01-15 23:39 UTC
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to... References: [TextAlign.Justify]
2. Click on... the link((https://developer.android.com/reference/kotlin/androidx/compose/ui/text/style/TextAlign.Companion#Justify()) property
)
3. See error... Sorry, we couldn't find that page

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2023-01-17 19:35
Duplicate of #151 , #150

**Comment by osuleymanova** [comment] 2023-01-20 16:42
Hello @mordeshen,

Thank you for reaching out to us. The link is fixed. Happy coding!

**Closed by osuleymanova** 2023-01-20 16:42 UTC
Labels: duplicate
