### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by wizzardx** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#479] opened 2023-10-30 11:04 UTC
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#2)

**In which task and step of the codelab can this issue be found?**

Task "Add images to your Android app", step 3

**Describe the problem**

Even after adding the import line "import androidx.compose.foundation.Image", there is still a "None of the following functions can be called with the arguments supplied." error.

**Steps to reproduce?**

1. Follow the instructions in step 9 of the guide, until just after adding the requested import line.
2. Attempt to compile the project

**Versions**

Android Studio version: 2022.3.1 Patch 2
API version of the emulator: 34

**Additional information**

Here are my compile errors:

```
e: file:///home/david/AndroidStudioProjects/HappyBirthday/app/src/main/java/com/example/happybirthday/MainActivity.kt:77:5 None of the following functions can be called with the arguments supplied: 
public fun Image(bitmap: ImageBitmap, contentDescription: String?, modifier: Modifier = ..., alignment: Alignment = ..., contentScale: ContentScale = ..., alpha: Float = ..., colorFilter: ColorFilter? = ..., filterQuality: FilterQuality = ...): Unit defined in androidx.compose.foundation
public fun Image(painter: Painter, contentDescription: String?, modifier: Modifier = ..., alignment: Alignment = ..., contentScale: ContentScale = ..., alpha: Float = ..., colorFilter: ColorFilter? = ...): Unit defined in androidx.compose.foundation
public fun Image(imageVector: ImageVector, contentDescription: String?, modifier: Modifier = ..., alignment: Alignment = ..., contentScale: ContentScale = ..., alpha: Float = ..., colorFilter: ColorFilter? = ...): Unit defined in androidx.compose.foundation
```

I can fix the error in my code by adding the required "contentDescription" parameter, like this:

```kotlin
Image(
        painter = image,
        contentDescription = "Description for accessibility",
    )
```

**Comment by simosechi** [comment] 2023-11-16 22:15
The tutorial isn't clear in that part, I think that import is not the solution for that error, despite what it's suggested. The fix is more related to the "Check your app for accessibility" section

**Comment by jeffchase** [comment] 2023-11-29 21:31
Was just about to post this same issue. The codelab should just acknowledge that the error will be fixed in the next section.

**Comment by mccumb01** [comment] 2024-01-06 20:17
Was about to post this too ... 

The problem is a missing step - the import fixes the "unresolved reference: Image" and REVEALS the error in the screenshot; it doesn't fix it. 
Adding the 2nd argument in the next step fixes it, and THEN they should discuss accessibility. 
Need to edit the tutorial text, but that's not available to fix here ...

**Comment by johnshea** [comment] 2024-03-14 16:51
Hi @wizzardx 

Thank you for writing in with your issue.

The team has revised the wording to address this issue for future students.

Hope you are enjoying the course!

Regards.

**Closed by johnshea** 2024-03-14 16:51 UTC
