### ISSUE TITLE
Add images: Android Basics in Compose

### ISSUE THREAD

**Issue by Rohitgithub010203** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#186] opened 2023-02-16 07:01 UTC
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

unable to download any image from github from the link provided

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2023-03-20 20:00
Hello @Rohitgithub010203,

Thank you for reaching out to us and sharing your concern. To help us troubleshoot this issue further, we will need more information: codelab URL, section, links for image downloading. Please share detailed reproduction steps as much as possible.

**Comment by osuleymanova** [comment] 2023-04-03 22:52
Closing this issue, since there is no reply.
Please create a new one, if you need help.
All the best learning Android.

**Closed by osuleymanova** 2023-04-03 22:52 UTC
