### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by Osiris9999** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#211] opened 2023-03-04 15:06 UTC
**https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#6**

**The issue is found on the 7th task of add images**

**There is a small mistake in the function call .**
**It is shown as:  modifier = modifier.fillMaxSize()**
**while the correct one would be modifier = Modifier.fillMaxSize()**

![Add_images_to_your_Android_app](https://user-images.githubusercontent.com/66261812/222913520-e98453f0-20b4-491f-8e66-4f1d6c2e7d7e.png)

**Comment by osuleymanova** [comment] 2023-03-06 18:57
Duplicate of #207

**Comment by osuleymanova** [comment] 2023-03-07 00:42
Hello @Osiris9999,
Thank you for reaching out to us.
It is a best practice to use the passed in Modifier argument in the root layout of the composable.
Instructions are updated and to be published

**Closed by osuleymanova** 2023-03-07 00:42 UTC
