### ISSUE TITLE
Install Android Studio: Android Basics with Compose

### ISSUE THREAD

**Issue by TaymourlankFarawilla** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#575] opened 2024-01-15 23:58 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-first-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-first-app#1

**In which task and step of the codelab can this issue be found?**
The whole codelab. 

**Describe the problem**
The whole codelab can't be marked as completed, because it has no 'Back', 'Next', or 'Done' buttons on the page (Step 3 in image).
also, the two videos aren't marked as completed although I watched them several times (Steps 1 and 6 in image).
So, Set up Android Studio Pathway 2 can't be 100% and it stops at 80% with 1/5 activities remaining.
I attached the last image from another codelab just to clarify what I mean about 'Back', 'Next', and 'Done' buttons.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![2024-01-16 (3)](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/156724990/27356155-b64d-4dd0-91b1-9d6a6dd5062d)
![2024-01-16 (2)](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/156724990/837bcf15-4287-4292-8a9d-19dfe21680bf)
![2024-01-16 (1)](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/156724990/1ee7d777-fd95-43cd-95cf-22c9a35d508e)
![2024-01-13](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/156724990/1dc031cf-813a-49c3-87a2-285549d73512)

**Comment by mzuociling** [comment] 2024-01-18 05:04
![replay1](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/154315377/55382e67-e3e5-4206-8a16-404ac9b9d337)
![replay2](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/154315377/1247b79e-3483-40f8-a5aa-11f55b15466c)

I encountered the same issue, and my solution was to click sequentially starting from 1 and then click 'Finish' at the end.

**Comment by TaymourlankFarawilla** [comment] 2024-01-18 18:33
The problem is there is no 'Finish' or 'Done' button to click, just the whole page without any buttons to click on.

**Comment by mzuociling** [comment] 2024-01-19 06:39
> The problem is there is no 'Finish' or 'Done' button to click, just the whole page without any buttons to click on.


Click the Done button with clicks from 1 to 11.
"Click from 1 to 11 in sequence and then click 'Done'." by ChatGPT translate


![reply](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/154315377/df190941-a23f-434b-aa6b-4839aaea708b)


![reply2](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/154315377/54e6d85a-7927-4f4e-b2c0-49651cd54fa0)

**Comment by dev-techwriter** [comment] 2024-03-01 00:37
Hi there - thanks for reporting this. I think there are some known issues involved here. I've provided some instructions for how to fix this. I've gotten it to work properly.  

# Mark the codelab as complete

The "Create your first Android app" codelab is formatted differently from the other codelabs, and doesn't have "Complete" buttons by design (it could be a better design, I know). 

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/44713801/7393cdc8-5063-42b9-9ec9-7e01ccc962f8)

To get around this and mark the codelab as complete, try clicking the **Conclusion** button at the bottom, which turns all of the buttons dark blue...

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/44713801/88f071ff-f897-4c25-969b-c683f2a8a820)

(You may have to click this button more than once.)

Anyway, when you go back to the [Setup Android Studio page](https://developer.android.com/courses/pathways/android-basics-compose-unit-1-pathway-2) screen, that codelab should be checked off, like this:

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/44713801/2752c66b-a357-4b8a-bf98-68adf3dcc205)

# Mark the pathway as complete

As you've pointed out, the Setup Android Studio Pathway stops at 80% with 1/5 activities remaining:

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/44713801/3089ba87-9c66-4807-a10c-058c8e76d311)

To achieve 100% completion for each pathway, you need to complete the quiz successfully and also any codelabs that are not marked optional. The videos here are marked optional, so they don't seem to count (at least here).

Therefore, if you follow the steps above in _Mark the codelab as complete_, and also successfully complete and submit the quiz, you should see the pathway as 100% complete, like this:

![image](https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/assets/44713801/7e80c9b2-a433-4b27-aa47-eec505e6615c)

**Comment by kkuan2011** [comment] 2024-12-11 20:42
Thanks Mike! Since there's no further comments on this bug, I'll close it now.

**Closed by kkuan2011** 2024-12-11 20:42 UTC
