### ISSUE TITLE
Text composables: Refactor BirthdayGreetingWithText

### ISSUE THREAD

**Issue by jv-ss** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#109] opened 2022-11-15 23:57 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#5

**In which task and step of the codelab can this issue be found?**
Pathway 6, topic 4

**Describe the problem**
In pathway 4 was described the naming conventions to follow when naming composable functions.
One of the rules is: DO NOT use a nouned preposition: TextFieldWithLink(). 
But in pathway 6 you just named a composable function as BirthdayGreetingWithText() . Oh my goodness   :/ :(
Please fix it ASAP

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment] 2023-02-08 20:52
Closing as duplicate of https://github.com/google-developer-training/basic-android-kotlin-compose-birthday-card-app/issues/109

**Closed by android-dev-lxl** 2023-02-08 20:52 UTC
Labels: In progress
