### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by user154lt** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#203] opened 2023-02-28 12:04 UTC
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#6)

Step 7: Align and arrange the text

A capital letter is missing in the code:

`Column(
   modifier = modifier.fillMaxSize()
) {
  //...
}
`

It should read:

`Column(
   modifier = Modifier.fillMaxSize()
) {
  //...
}
`

**Comment by osuleymanova** [comment] 2023-03-06 19:08
Duplicate of #194

**Comment by osuleymanova** [comment] 2023-03-07 00:43
Hello @user154lt,

Thank you for reaching out to us.
It is a best practice to use the passed in Modifier argument in the root layout of the composable.
Instructions are updated and to be published

**Closed by osuleymanova** 2023-03-07 00:43 UTC
