### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by Yaliandri** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#70] opened 2022-09-26 20:13 UTC
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-text-composables?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-text-composables#10

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
when you copy and paste de code in Android Studio, it marks many errors... i think it must be because of the updates 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![image](https://user-images.githubusercontent.com/114441760/192370961-2455376d-a4a9-42f1-ba3b-269ad2540eac.png)
![image](https://user-images.githubusercontent.com/114441760/192370998-e0877446-347a-4b18-bb16-8ae31a09889b.png)

**Comment by osuleymanova** [comment] 2022-10-18 19:23
@Yaliandri 
Thanks for contacting us and providing the screenshots. 
Could you expand problems file and share it with us in order we can help with troubleshooting?

![Screen Shot 2022-10-18 at 12 17 54 PM](https://user-images.githubusercontent.com/86437155/196524329-5a179d67-7be2-4bfe-be27-4f7599cb16be.png)

**Comment by osuleymanova** [comment] 2022-10-26 17:47
The issue is closed as no further clarification provided.

**Closed by osuleymanova** 2022-10-26 17:47 UTC
