### ISSUE TITLE
Add images: Android Basics in Compose

### ISSUE THREAD

**Issue by JuanDiegoCastellanos** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#51] opened 2022-08-27 22:53 UTC
https://developer.android.com/codelabs/basic-android-kotlin-compose-composables-practice-problems?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-composables-practice-problems#4

I have some errors with compose quadrant, thats no work on Modifier.weight, please update the codelab or write to me about how to fix this error.

Thanks

**Comment by osuleymanova** [comment] 2022-09-19 22:13
@JuanDiegoCastellanos 
Please provide the the screenshot of the error so we could help with troubleshooting.

**Comment by osuleymanova** [comment] 2022-10-13 17:55
The issue is closed as no further clarification of it was provided.

**Closed by osuleymanova** 2022-10-13 17:55 UTC
