### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by sseebart** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#196] opened 2023-02-22 23:33 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#6

**In which task and step of the codelab can this issue be found?**
7. Align and arrange the text, step 3

**Describe the problem**
the line:
    modifier = modifier.fillMaxSize(),

throws an error and should likely read:
    modifier = Modifier.fillMaxSize(),

**Steps to reproduce?**
 See error...
Unresolved reference: modifier

**Comment by osuleymanova** [comment] 2023-03-06 19:11
Duplicate of #194

**Comment by osuleymanova** [comment] 2023-03-07 00:44
Hello @sseebart,

Thank you for reaching out to us.
It is a best practice to use the passed in Modifier argument in the root layout of the composable.
Instructions are updated and to be published

**Closed by osuleymanova** 2023-03-07 00:44 UTC
