### ISSUE TITLE
Add images: import androidx.compose.foundation.Image 

### ISSUE THREAD

**Issue by someguyinbaltimore** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#94] opened 2022-10-19 13:08 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#3

**In which task and step of the codelab can this issue be found?**
[4. Add an Image composable](https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-1-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-add-images#3)

**Describe the problem**

Using sample code from the code-along video and the step 4. I'm receiving 4 errors when building the preview. 

Sample Code:
```
@Composable
fun BirthdayGreetingWithImage(message: String, from: String){
    val image = painterResource(id = R.drawable.androidparty)
    Image(painter = image, contentDescription = null)
}
```
Errors:
-Cannot access '<init>': it is package-private in 'Image'
-Cannot create an instance of an abstract class
-Cannot find a parameter with this name: painter
-Named arguments are not allowed for non-Kotlin functions
-Cannot find a parameter with this name: contentDescription
-Named arguments are not allowed for non-Kotlin functions

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
Android Studio Dolphin | 2021.3.1 Patch 1
_API version of the emulator:_ 
API3 3

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
<img width="574" alt="Screen Shot 2022-10-19 at 9 06 22 AM" src="https://user-images.githubusercontent.com/9001416/196699817-26df6598-414f-458f-856d-f6044c6122db.png">

**Comment by someguyinbaltimore** [comment] 2022-10-19 14:04
It seems like Android studio doesn't suggest importing `import androidx.compose.foundation.Image` . The tutorial also doesn't mention importing it.

**Comment by android-dev-lxl** [comment] 2023-02-02 22:41
Duplicate of #156 
Please follow instruction in #156 
Please let us know, if it does not work.

**Closed** 2023-02-08 20:47 UTC
Labels: To be published
