### ISSUE TITLE
Add images: Android Basics with Compose

### ISSUE THREAD

**Issue by dcparsons** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#627] opened 2024-03-13 17:32 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-add-images

**In which task and step of the codelab can this issue be found?**
Step 3

**Describe the problem**
When using Iguana 2023.2.1 the image, androidparty.png, does not display in preview mode, instead the user is presented with a 'NoSuchFieldError'.  

**Steps to reproduce?**
Follow the steps in the codelab.  

Worth noting, if the user were to go and update `setContent` to call `GreetingImage` the image would load in the emulator, but it would still be broken in Preview mode. 

After restarting Android Studio, preview worked as expected.

**Versions**
_Android Studio version:_ Iguana 2023.2.1, Windows.

**Comment by RudraOp9** [comment] 2024-03-17 08:20
can you provide more info about the error : "no such field error" 

an preview does not have any connections setContent of an Activity. 
if you want to see your composable function as preview : 
- annotate the function with @Preview
- you can pass parameter such as showBackGround etc.. to @Preview()


see more about the preview feature on [android website](https://developer.android.com/jetpack/compose/tooling/previews).

**Comment by dcparsons** [comment] 2024-03-18 11:08
I am not sure what more information you are looking for.  'NoSuchFieldError' is what is being generated in Android Studio when trying to load the image in Preview Mode.

**Comment by johnshea** [comment] 2024-04-30 14:59
As I am unable to reproduce, I will be closing this issue.

If it still occurs on the latest stable version of Android Studio, please create a new issue and provide your full project.

Regards.

**Closed by johnshea** 2024-04-30 14:59 UTC
