### ISSUE TITLE
Text composables: Android Basics with Compose

### ISSUE THREAD

**Issue by sanhla376** [google-developer-training/basic-android-kotlin-compose-birthday-card-app#26] opened 2022-06-18 06:47 UTC
[yangonsanhla376@email.com](yangonsanhla376@email.com) **URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by sanhla376** [comment] 2022-06-18 06:48
Myanmar.. Yangon . Dagon.
yangonsanhla376@email.com

**Comment by osuleymanova** [comment] 2022-07-20 23:56
@sanhla376 
Could you please be more specific about the issue?

**Comment by osuleymanova** [comment] 2022-07-27 00:05
The issue is closed as no further clarification of it was provided.

**Closed by osuleymanova** 2022-07-27 00:05 UTC
